services:
  tendering-db:
    image: postgres:latest
    container_name: tendering_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - tendering_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tender_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  tendering_data: