services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      tendering-db:
        condition: service_healthy
    environment:
      POSTGRES_JDBC_URL: jdbc:postgresql://tendering-db:5432/tender_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  tendering-db:
    image: postgres:latest
    container_name: tendering_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - tendering_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tender_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  tendering_data: